// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEQyIC2yRH04GiQ2zy_4thRTd6absNj0',
    appId: '1:815940817053:web:6edf8717f5da6b7fefc474',
    messagingSenderId: '815940817053',
    projectId: 'calory-calculator-f4259',
    authDomain: 'calory-calculator-f4259.firebaseapp.com',
    storageBucket: 'calory-calculator-f4259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGFGKkUaAsc81DfiuP9sQZtR3aerlcaE',
    appId: '1:815940817053:android:4ff7f27dd4479bedefc474',
    messagingSenderId: '815940817053',
    projectId: 'calory-calculator-f4259',
    storageBucket: 'calory-calculator-f4259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS8uqipqbqrVlsx3fEFaGelQ_Vv_5bPDU',
    appId: '1:815940817053:ios:217e535c4628efe9efc474',
    messagingSenderId: '815940817053',
    projectId: 'calory-calculator-f4259',
    storageBucket: 'calory-calculator-f4259.appspot.com',
    iosClientId: '815940817053-t4najqmqaveu5jn916cqn0o10e7rc6q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloryCalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS8uqipqbqrVlsx3fEFaGelQ_Vv_5bPDU',
    appId: '1:815940817053:ios:217e535c4628efe9efc474',
    messagingSenderId: '815940817053',
    projectId: 'calory-calculator-f4259',
    storageBucket: 'calory-calculator-f4259.appspot.com',
    iosClientId: '815940817053-t4najqmqaveu5jn916cqn0o10e7rc6q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloryCalc',
  );
}
